options:
  logging: CLOUD_LOGGING_ONLY

steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      ["build", "-t", "gcr.io/premium-hybrid-443311-u4/fast-api:latest", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/premium-hybrid-443311-u4/fast-api:latest"]

images:
  - "gcr.io/premium-hybrid-443311-u4/fast-api:latest"
